from pathlib import Path
base=Path(__file__).parent
exec((base/'build_sponsor_manual.py').read_text(encoding='utf-8').split('# Cover')[0])
OUT=base/'ElimuTaifa_Content_Management_Guide.docx'
d.core_properties.title='ElimuTaifa Content Management Guide'
d.core_properties.subject='Creating editing scheduling and retiring public announcements'
s.header.paragraphs[0].text='ELIMUTAIFA  |  Content Management'
s.footer.paragraphs[0].runs[0].text='Content Management guide  •  '
p('ELIMUTAIFA').runs[0].bold=True
d.add_paragraph('Content Management Guide','Title')
d.add_paragraph('Announcements news and education updates','Subtitle')
p('Version 1.0  |  4 October 2026')
p('Use this guide to create, edit, schedule, publish and archive public content in ElimuTaifa. It covers text, images, YouTube videos, source links and announcement display options. Field and button names match the English admin interface.')
h('Access and scope')
p('Admin and Owner accounts can add, edit, publish, schedule and archive content. Only an Owner can permanently delete an archived item. The current workflow does not include a separate Owner approval stage before an Admin publishes.')
p('This guide covers Admin → Content. Sponsors & Ads controls separate banners, direct sponsors and display placements. Result Pages controls examination and selection cycles. Choosing the Exam results category does not publish or change a result cycle.')
p('No screenshots, live publication tests or content approvals are invented here. The examples are instructions, not records of actions already completed.')

page('Contents and quick start')
table(['Section','Topic'],[('1','Create and write content'),('2','Images and YouTube videos'),('3','Source and destination links'),('4','Publication and scheduling'),('5','Featured content and pop ups'),('6','Edit archive and delete'),('7','Troubleshooting'),('8','Publishing checklist')],[.8,6.1])
h('Quick start')
steps(['Sign in and complete authentication.','Open Content → + Add content.','Complete Basic details, then choose media if needed.','Complete Source and link.','Save as Draft while preparing the item.','Review the text, links, audience and dates.','Choose Published for immediate release, or Scheduled with a future publish time.','Select Save content and check the public Announcements page.'])
p('The editor does not provide a public draft-preview link. Preview is shown for a saved Published item with an internal destination. Do not publish unfinished material just to obtain a preview.')

page('1 Create and write content')
steps(['Open Content and select + Add content.','Choose Category and Audience.','Enter Title, SEO slug, Short description and Full text.','Keep Status as Draft and select Save content.'])
table(['Field','Requirement'],[('Category','Announcement, News, Exam results, Selection, Admission or Scholarship'),('Audience','Everyone, Students, Parents, Teachers, Schools or Organisations'),('Title','5–140 characters'),('SEO slug','Unique URL name, up to 160 characters; lowercase letters, numbers and hyphens'),('Short description','20–300 characters; summarise what the reader needs to know'),('Full text','20–20,000 characters; plain text with line breaks preserved')],[2.0,4.9])
p('Audience describes who the content is for. It is not a private access restriction: published items remain public.')
h('Writing guidance')
bullets(['Start with the announcement and the action the reader should take.','Use short paragraphs and specific dates rather than “today” or “soon”.','Confirm deadlines and official claims against the actual source.','Avoid pasting HTML, scripts or a styled Word document into Full text.','Use an SEO slug that describes the item, such as scholarship-application-guide.'])
p('Example slug and writing advice do not guarantee search-engine ranking or traffic. Keep the slug stable after sharing the public link.')

page('2 Images and YouTube videos')
p('Choose one media type per item: No media, Image or YouTube. Images and embedded video require When the link is clicked → Open on the announcements page.')
h('Add an image')
steps(['Choose Media type → Image.','Use Upload image or Image HTTPS link.','Upload JPG, PNG or WebP, up to 5 MB; or supply a full HTTPS image URL up to 1,000 characters.','Add an optional Media description of up to 200 characters.','Check the image preview, then select Save content.'])
p('If both a file and an image link are supplied, the uploaded image is used. When editing an existing image item, leaving the inputs unchanged can keep its saved image. Choose No media to remove media from the item.')
p('Use a clear image that you have permission to publish. Uploading avoids relying on another website’s image remaining available.')
h('Add a YouTube video')
steps(['Choose Media type → YouTube.','Paste a valid YouTube Watch, Share, Shorts, Live or Embed link into YouTube URL.','Add Media description if helpful.','Check the admin link preview and save.','Check playback on the public item.'])
p('Only one YouTube video is supported per item. The admin preview does not play it. Public video playback starts when the reader presses Play; it does not start automatically.')
p('Do not paste iframe code or scripts. The link must identify a supported YouTube video, not just a channel or playlist. Provider restrictions or video removal can still prevent playback.')

page('3 Source and destination links')
table(['Field','Purpose'],[('Source name','Name of the organisation or publication; optional, up to 120 characters'),('Source URL','Link supporting the information; optional, up to 1,000 characters'),('When the link is clicked','Open on the announcements page, or Open another website'),('External destination URL','Required when opening another website; up to 1,000 characters')],[2.3,4.6])
p('Source URL and External destination URL are different. Source URL supports your information. External destination URL decides where the reader goes when opening an external item.')
h('Internal article')
p('Choose Open on the announcements page to keep the full content inside ElimuTaifa. Readers use Soma zaidi to expand the item. An internal item can contain text and one image or video.')
p('An internal public item uses an announcement anchor based on its slug. Changing the slug can break links already shared, so avoid changing it unless necessary.')
h('External item')
p('Choose Open another website and enter the destination URL. Choose No media: external items cannot include an article image or embedded video in this setup. The editor still requires Short description and Full text, although the public item directs the reader to the external website.')
p('The content form accepts full HTTP or HTTPS source and destination URLs; prefer HTTPS where the source supports it. Image links specifically require HTTPS. Open the link yourself to confirm it leads to the intended page.')

page('4 Publication and scheduling')
table(['Status','Behaviour'],[('Draft','Saved for preparation; not publicly listed'),('Scheduled','Becomes eligible at Publish date/time'),('Published','Publicly eligible after its publish time, before any expiry'),('Archived','Hidden from the public content list')],[1.7,5.2])
h('Publish now')
steps(['Review all required fields.','Choose Status → Published.','Leave Publish date/time blank to use the current time when saving, or set the intended publication time.','Select Save content.','Open Announcements and check the item.'])
p('A Published item with a future publish time is not visible until that time. To plan a future release clearly, use Scheduled.')
h('Schedule a release')
steps(['Choose Status → Scheduled.','Set a future Publish date/time. This field is required for Scheduled content.','Optionally set Expire date/time after the publish time.','Select Save content.','Check the public item after its scheduled release time.'])
p('Dates use Africa/Dar_es_Salaam time, EAT. The application checks visibility against time when content is requested. Status refreshes occur when the relevant pages are accessed; scheduling does not require an Owner to manually press Publish at the release time.')
h('Expiry')
p('Expire date/time is optional and must be after publication. Public queries hide expired items; status refresh can mark them Archived and clear their pop-up flag. Leaving expiry blank means there is no automatic end date for visibility.')

page('5 Featured content and pop ups')
h('Show at the top of announcements')
p('Select this checkbox to prioritise the item in public content ordering. Featured items appear before ordinary items; publication dates determine ordering within those groups. More than one item can be featured.')
p('Featured does not override Draft, future publication or expiry. It is also not a Sponsors & Ads page-targeting control.')
h('Show as a pop up')
p('Select this checkbox only for an important announcement that should interrupt a supported public page. Saving a Published or Scheduled item with this option clears the pop-up flags on other content items, so the choice can replace the existing content pop-up.')
p('A Scheduled pop-up selection can therefore clear the earlier item’s flag before the scheduled item becomes eligible. Review the timing before saving.')
p('This checkbox does not provide placement targets, priority, Skip delay or pop-up frequency settings. Those controls belong to the separate Sponsors & Ads placement editor. Do not assume the two systems share identical behaviour.')
h('Check the public experience')
steps(['Open the public Announcements page after publication.','Confirm the title, short description, category, audience and date.','Expand an internal item and review its full text, source and media.','Check an external item’s destination.','Review on a phone and desktop.','If using a pop-up, check a public page where that component is present.'])
p('Public filters let readers search announcements and choose a category. Use accurate titles, descriptions and categories so the item can be found easily.')

page('6 Edit archive and delete')
h('Find and edit an item')
steps(['Open Content.','Choose Status or Category and select Filter if needed.','Find the item and select Edit.','Make the required changes and select Save content.','Check the public item again if it is Published.'])
p('The list shows up to 100 matching items ordered by recent updates. A missing item may be outside that limit or excluded by a filter. Coordinate edits with other editors; do not assume an approval or revision-restore workflow exists.')
h('Archive an item')
steps(['Find the item in Content and select Archive.','Confirm the action.','Check that its status is Archived.'])
p('Admin and Owner accounts can archive. Archiving keeps the saved content and clears its pop-up flag. To reuse it, open Edit, review dates and content, choose Draft, Scheduled or Published as appropriate, then save.')
h('Owner only permanent deletion')
steps(['Archive the item first.','As an Owner, select Delete permanently from the archived row or edit page.','Read the confirmation and confirm only if permanent removal is intended.'])
p('Permanent deletion has no Undo action. It deletes the content record and attempts to remove its managed uploaded image. It does not delete an image hosted elsewhere or a YouTube video. Audit activity remains recorded.')
p('Content saves, archive and delete operations attempt to update the sitemap. “Content saved, but the sitemap could not be updated” means the content was saved; the sitemap needs developer attention. Sitemap updates do not guarantee indexing or search traffic.')

page('7 Troubleshooting')
table(['Problem','Action'],[('This URL name is already used','Choose a different unique SEO slug.'),('Required text is rejected','Check Title, Short description and Full text minimum and maximum lengths.'),('Image upload rejected','Choose Image first; use JPG, PNG or WebP up to 5 MB.'),('Image or video with external destination','Choose an internal destination, or switch to No media.'),('YouTube URL rejected','Paste a supported video URL rather than iframe code, channel or playlist.'),('Scheduled content is rejected','Set a valid Publish date/time.'),('Expiry rejected','Set expiry after publication.'),('Published content is not visible','Check publish time, expiry and public status; confirm the intended item is saved.'),('Preview is missing','Public Preview is for a saved Published internal item; not Draft or external content.'),('Pop up changed or disappeared','Check current pop-up flags, status, timing and whether the page supports the component.'),('Sitemap update warning','Content may already be saved. Ask the developer to inspect the sitemap operation.'),('Request expired','Reload, sign in again if needed, and resubmit carefully.')],[2.6,4.3])
p('For assistance, record the item title or ID, affected screen, time in EAT and exact error. Avoid sending confidential information or account credentials.')

page('8 Publishing checklist')
h('Before publishing')
check(['The title clearly describes the update.','The category and audience are appropriate.','Dates, deadlines and claims have been checked against the actual source.','Short description and Full text are complete and readable.','The SEO slug is unique and suitable for sharing.','Source and destination links lead to the intended pages.','Media is valid and permission to publish has been checked.','Publication and expiry use the correct EAT dates.','Featured and pop-up options are intentional.','An important existing pop-up will not be unintentionally replaced.'])
h('After publishing')
check(['The item is visible on the public Announcements page.','The full text or external destination works as intended.','The source link and media work.','Phone and desktop layouts have been reviewed.','Any save or sitemap warning has been recorded for follow-up.'])
p('Tick items only after completing the checks. This document does not certify that any content item has been approved, published or tested.')
d.save(OUT)
print(OUT)
